# Generated by Django 5.0 on 2023-12-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phn', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('is_subordinate', models.BooleanField()),
                ('is_lead', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('title', models.CharField(default=None, max_length=10)),
                ('description', models.TextField(blank=True, default=None, max_length=10, null=True)),
                ('deadline', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanagement.employee')),
            ],
        ),
    ]
